### ISSUE TITLE
Can't turn off Report PSM Ambiguity

### ISSUE THREAD

**Issue by blfrey** [smith-chem-wisc/MetaMorpheus#1322] opened 2018-07-27 19:30 UTC
I usually uncheck the Report PSM Ambiguity checkbox.
In version 282, that worked as expected.
In version 285, it did not.  The output shows peptide ambiguity. (I double checked the prose.txt to be sure and it was set to FALSE).

**Comment by rmillikin** [comment] 2018-07-30 15:21
I searched a yeast file with default settings (trypsin, classic search, etc) and the ambiguity checkbox worked as expected - I unchecked it and didn't get any PSMs with ambiguous sequences. I looked in the PSM and Peptides.psmtsv files and searched for the "|" character in the full sequence and base sequence columns. Can you attach your .toml file? That might help reproduce the issue

**Comment by blfrey** [comment] 2018-07-30 17:25
\\bison\share\Users\Frey\_temp transfer stuff\Report Ambiguity problem in MMv285
I put relevant files in this folder on my Bison.   Dragging the toml file here had GitHub saying they don't support that file type.
thanks.

**Comment by rmillikin** [comment] 2018-07-31 17:26
I still haven't been able to reproduce this - using the .toml and file provided in 285 gives the expected (no ambiguity) output. I'm going to leave this issue open in case we can eventually figure out how to reproduce this...

**Comment by rmillikin** [comment] 2018-08-01 19:51
I was able to reproduce this in 285 when I drag in the .toml (ReportAllAmbiguity = false) and then set a file-specific parameter (protease = trypsin). I ran the search and the resulting PSM files contain ambiguity. I double-checked the output .toml and it does indeed still say ReportAllAmbiguity = false.

This should have already been fixed in #1305 but I will double-check to make sure that it's no longer a bug.

For this search did you specify any file-specific settings? If so, that's probably the problem. If not, we'll have to track down another bug...

**Comment by rmillikin** [comment] 2018-08-01 19:55
Yep if this is the bug described in my previous post, it's fixed in 286

**Comment by rmillikin** [comment] 2018-08-02 14:26
I realized this morning that since it's a calibrated file, and calibration writes suggested ppm tolerances (file-specific settings) that that's what likely caused the problem. So you probably didn't set any file-specific settings but since you calibrated and that generated file-specific settings, the subsequent search task got messed up

**Comment by blfrey** [comment] 2018-08-02 14:41
OK, so that explains that.   so then, you think v286 should be fine?

**Comment by rmillikin** [comment] 2018-08-02 14:44
Yeah, this is fixed in 286. I'm going to close this issue but if it recurs of course feel free to reopen or make a new issue.

**Closed by rmillikin** 2018-08-02 14:44 UTC
Labels: Bug
