### ISSUE TITLE
Does scrambling reverse decoys that match target help?

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#485] opened 2017-07-21 13:21 UTC
occasionaly a reverse decoy has the same sequence as a target peptide. If we assign all hits to that sequence as decoys then we're missing some real hits. Alternatively, we can compare reverse decoys to targets and then scramble the sequence of any decoys that match. In that way, we keep number of decoys are targets equal but there is no overlap in sequence.

**Comment by stefanks** [comment] 2017-07-21 14:11
This would bias the target/decoy strategy in unpredictable ways. 

How about this alternative: mark the sequences that match both targets and decoys in the PSMs file. This way we would know that those matches might be targets, but the FDR calculations would remain as they are now.

**Comment by trishorts** [comment] 2017-07-21 16:03
I don't buy that it is unpredictable.
I see value in your second point.

Thoughts:
1. there is already bias since matches go to decoy (ie decoy database is larger than target database). Unequal probability for random match.
2. scramble database and reverse database are both widely used in TDA. 
3. Combining two valid approaches would eliminate bias in 1. above and also let us see real targets.

**Comment by acesnik** [comment] 2017-07-21 16:07
Why not use a scrambled database to begin with? That way, if a decoy sequence is the same as a target sequence, we can shuffle and try again.

**Comment by trishorts** [comment] 2017-07-21 16:10
I'd like to see results from a comparison of the two types of decoys. I have inherent bias, which could be remedied with data.

**Comment by zrolfs** [comment] 2017-07-21 16:11
There are still reproduciblity concerns with scrambled, since one software may randomize differently from another, whereas all search software reverses peptides the same way.

**Comment by acesnik** [comment] 2017-07-21 16:18
So maybe we could compare results for reverse, reverse (with scrambled replacements), scrambled, and scrambled with another randomization.

**Comment by trishorts** [comment] 2017-07-21 16:28
Yes to AC proposal.

Some of my bias comes from using random sequences as decoys for proteoform suite. That was a major fail. Came to learn that mother nature doesn't organize her amino acid sequences randomly. That makes me think that randomized decoys won't make a very "authentic" decoy database. The same might said for reverse I guess.

**Comment by zrolfs** [comment] 2017-07-21 16:32
Is it more important to generate decoy sequences that "replicate mother nature", or to generate decoy sequences that are common trip ups for mass spec? i.e. complementing target "SEQIENCE" with decoy "SEGALEGGCE" is super tricky for mass spec to discern. If we want to replicate mother nature, why not just use a different species proteasome where there is no overlap?

**Comment by trishorts** [comment] 2017-07-21 16:34
I like that option. One aspect of the reverse(I believe) is that there is automatically the same number of distrbution of peptide lengths. Other organisms might have different peptide length distributions than the sample in question.

**Comment by zrolfs** [comment] 2017-07-21 16:39
A last question just to drive the dagger in a bit... What should we do for scrambled when you CAN'T generate a scrambled sequence that's not in the target database? As an example, for MHC-II, the first three decoys that hit are "LLLLLLL", "LLLLLLLL", and "LLLLLLLLL". Taking residues from other sequences will not preserve the peptide precursor mass distribution (which, in my mind, is more important than length distributions when conducting narrow mass searches).

**Comment by lschaffer2** [comment] 2017-07-21 16:52
One option is to do what we do in proteoformSuite with tryptic peptides. Digest, concatonate all peptides, shuffle array, and cleave with lengths of real peptides so we have real sequences/same length distribution.

**Comment by stefanks** [comment] 2017-07-21 17:53
And don't forget modifications...

**Comment by lschaffer2** [comment] 2017-07-21 18:03
In PS we add adds to decoys corresponding to the length used

**Comment by stefanks** [comment] 2017-07-31 14:37
Now we are not "missing some real hits", because the new detailed output in PSMs files illuminates this case, and outputs both the target and decoy matches, so inspecting the PSMs file would tell you exactly where this is an issue.

**Comment by rmillikin** [comment] 2018-10-13 14:56
merged with #544

**Closed by rmillikin** 2018-10-13 14:56 UTC
Labels: Discussion
