### ISSUE TITLE
Scan Number (different then in .mgf ?)

### ISSUE THREAD

**Issue by gvinterhalter** [smith-chem-wisc/MetaMorpheus#1274] opened 2018-07-09 16:17 UTC
Hi,

I have an .mgf that I converted to .mzML (so only MS2).
The resulting Scan Numbers in .psmtsv or .mzid  seem to be different then the original .mgf "SCANS".
Am I missing something? I need the number exactly as is in .mgf

Tnx in advance

**Comment by trishorts** [comment] 2018-07-09 16:19
will look into this shortly

**Comment by trishorts** [comment] 2018-07-09 16:57
which converter did you use?

**Comment by gvinterhalter** [comment] 2018-07-09 18:43
1. MSconvetGUI default options
2. I get an index out of bound of the array error

**Comment by zrolfs** [comment] 2018-07-09 18:45
Are you able to share your .mgf file with us? It will help us more quickly identify a fix.

**Comment by gvinterhalter** [comment] 2018-07-09 18:55
Here is the  [mgf and the search settings](https://drive.google.com/open?id=1kr99ROaK7AmXfbGDcQTZ4brszuzNV1Wf)

**Comment by zrolfs** [comment] 2018-07-09 19:18
The scans don't appear to be in order. The first 5 MS2 scan numbers are:
3585
3458
5041
9672
8147

Do you know why this is?
It is the cause of both problems 1 and 2.

MSConvert is handling this well, so it's something we can address on our end. I'll keep you posted and we should have a fix in 0.0.284.

If it's time sensitive, I can sort the mgf for you and send it back?
Thanks for letting us know!

**Comment by gvinterhalter** [comment] 2018-07-09 19:55
I see. 
So they should just be ordered by the scan number? 
I can do that, tnx.

mgf was exported from Prognosis (not by me)

**Comment by gvinterhalter** [comment] 2018-07-09 20:55
Sorting the mgf fixes 2 but I still think something is wrong with the output.
In the resulting files I'm getting a couple of Scan numbers that are not included in the original .mgf,
for example `2693`.

**Comment by gvinterhalter** [comment] 2018-07-10 06:01
No, these are the ones I can't find in the mgf, but as you say they are all probably off.

[unknown_PSM_psmtsv.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2179055/unknown_PSM_psmtsv.txt)
 (I had to make .txt because of the github)

--

**Comment by gvinterhalter** [comment] 2018-07-10 09:57
Actually yes, it's an offset BUT:

1. using (sorted) mgf and mzml gives different resutls
2. mgf produces much less rows (498) and missing scans are offseted by +1 (as far as I can see)
3. using mzml (converted froms sorted mgf) produces more rows (1174) but scan numbers are completely random.

it looks like that if I use mgf I can just offset the missing scans and it will work 

:D

**Comment by gvinterhalter** [comment] 2018-07-10 10:01
correction I can't fix it like that. looks like there are some that also don't aline with mgf scan (when using mgf)

**Comment by zrolfs** [comment] 2018-07-10 11:46
Thanks for the update. Mzml are currently indexed in order of appearance, so the first scan (regardless of what the scan number is) is 1, and the next is 2, and so on. We've fixed that for 0.0.284.

Your information helped, and I think I found the reason for 2 and 3. There are multiple of the same scan number (ie there are 6 scans labeled as SCANS=4508). Stranger still, they do not contain the same product ions. 
In mgf, these duplicate scan numbers are overwriting each other, while in mzml the reassignment of 1, 2, 3, etc. allows all of them to exist, resulting in more PSMs.

This is a pretty strange MS file. I'm not sure how to handle the duplication problem since the duplicates aren't chimeras (they don't have the same MS2 peaks). I think the best solution is to just assign scan numbers in the order of appearance (Mzml already does this). Other ideas appreciated @trishorts @rmillikin @acesnik

**Comment by zrolfs** [comment] 2018-07-10 11:52
As a temporary, hacky workaround, here's a key that can help you convert the MetaMorpheus mzml output into the original scan numbers.
[MetaMorpheusScansToActualScans.txt](https://github.com/smith-chem-wisc/MetaMorpheus/files/2180192/MetaMorpheusScansToActualScans.txt)

**Comment by zrolfs** [comment] 2018-07-10 11:58
I don't think the conversion list worked, so maybe something else is off. I'll keep you posted.

**Comment by gvinterhalter** [comment] 2018-07-10 12:41
Hi @zrolfs 
.mgf was exported from Progenisis QI. There are features (top 3 features get exported).
But, it wold appear that something is wrong with the export and we need to check what that is.
The mgf doesn't look like it should be. 

Another problem is that the lab doesn't work for the next 10 days and generally we won't be here for a while (vacations). Who knows when people will find the time to resolve this.

For know thank you all for such a quick and detailed help, you guys are awesome :)

**Comment by zrolfs** [comment] 2018-07-12 17:48
Hi @gvinterhalter,
We're going to close this issue for now. We've made changes so that 
-mgfs with disordered scans won't crash
-mgfs and mzml's with specified scan numbers will keep their correct scan numbers
-If a file contains multiple of the same scan number, MetaMorpheus will stop and alert the user as to which scan number was found multiple times.

Thanks for finding this issue and letting us know about it! Keep us posted once you get the file conversion figured out.

**Comment by trishorts** [comment] 2021-01-22 13:40
I just wanted to add a comment to this issue to possibly help with future problems dealing with progenisis mgf files. 

Progenisis will take multiple data files and then combine them. It will align the files before recombining. And it will assign the same scan number to all scans that come from the same mass precursor. That is why there is so many scans with the same scan number.

**Closed by trishorts** 2021-01-22 13:40 UTC
Labels: Bug, Question (support)
