### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by ncarrut** [smith-chem-wisc/MetaMorpheus#1146] opened 2018-04-27 17:28 UTC
When I try a search I get the runtime Error:  "Run failed, Exception:  Index was outside of the bounds of the array.  The example data works OK but when I use my own .raw file it fails.  I'm using thermo msfilereader 3.0 SP2
The raw file is at:
https://waynestateprod-my.sharepoint.com/:i:/g/personal/aj7682_wayne_edu/EQDUSPoPoqJApXBm7PJRBHMBUbR-JKw63C5trdjb2G3hiQ?e=2aEZji

**Comment by zrolfs** [comment] 2018-04-27 17:34
Hi ncarrut,
Thanks for letting us know. Can you post the results.txt that the crash wrote to the output directory, as well as the .toml file that was written to the same directory? These will help us track down the issue quicker. You should be able to drag them into this thread.

**Comment by rmillikin** [comment] 2018-04-27 17:55
Thanks for the report, I was able to reproduce this crash. It seems to be a problem with MSFileReader. I was able to convert it to .mzML format with MSConvert and then search it successfully in MetaMorpheus. I'll see if I can get another version of MSFileReader to read this file.

**Comment by rmillikin** [comment] 2018-04-27 18:05
One more note: MetaMorpheus was designed for high-res MS1 and MS2 data. When I searched the file with 20ppm tolerance I only got ~700 PSMs below 1% FDR, and when I used a 0.5 Da tolerance I got ~6800, which I assume means this data is low-res MS2. Just a quick "your mileage may vary" note to avoid future frustration.

**Comment by rmillikin** [comment] 2018-05-02 19:25
I've fixed this crash in #1148, it will be included in the next release (probably within a week)

**Closed by rmillikin** 2018-05-02 19:25 UTC
Labels: Crash

**Comment by ncarrut** [comment] 2018-05-03 16:33
Hi thanks for fixing this. Looking forward to trying it again
Regards
Nick

**Comment by ncarrut** [comment] 2018-05-17 20:06
Hi,
Got the new release-it works fine.  Thanks!
