### ISSUE TITLE
Product ion matching is poor for MetaDraw, maybe for scoring as well?

### ISSUE THREAD

**Issue by zrolfs** [smith-chem-wisc/MetaMorpheus#1823] opened 2020-01-31 16:59 UTC
y8 ion is particularly bad in this example:
MetaDraw Annotation:
![image](https://user-images.githubusercontent.com/16883585/73558412-bd0ef780-4418-11ea-93d6-bf5eac1058dd.png)

SeeMS Annotation:
![image](https://user-images.githubusercontent.com/16883585/73558386-af597200-4418-11ea-9688-cd96106bddd4.png)

**Comment by rmillikin** [comment] 2020-02-04 17:21
MetaDraw will annotate the closest peak to the monoisotopic mass found by the search (so this is a duplicate of #1197 I believe).. if it's an envelope rather than a single peak, it will annotate the mono mass and not the most intense peak in the envelope.

**Closed by rmillikin** 2020-02-04 17:21 UTC
