### ISSUE TITLE
Organize modifications files/modification types

### ISSUE THREAD

**Issue by trishorts** [smith-chem-wisc/MetaMorpheus#296] opened 2017-03-27 17:57 UTC
customizing the modification text files for an individual search with no preservation of the core modfication text files could lead to accumulation of errors and mistakes as the files migrate further from original with ever increasing array of searches. Rather have teh ability to select mods for usage at runtime (e.g. varible phospho, methyl, acetyl etc.) rather than editing files. Not to mention it kinda sucks having to look up the names/formulas/masses for stuff that we should already have somewhere.

**Comment by stefanks** [comment] 2017-03-27 18:33
Ugh, the modifications are such a mess right now!

I propose we first fix the Search task modifications, and then see what needs to be done with Gptmd and Calibration tasks.

Here are some thoughts:

- In a search task, Uniprot modifications only make sense in the context of localization: setting them as fixed or variable **never** makes sense. So, instead of the vague ptmlist.txt entry in the mod selection table, have a separate checkbox, "localize uniprot PTMs"
- The modification filenames are non-descriptive. Instead of displaying all the files in the Mods folder, use a collapsible tree view with the top level being the modification type, and the children being the modifications of that type. Automatically load all files, and categorize modifications by their modification type.
- Instead of the three or four checkboxes next to each modification, corresponding to variable, fixed, localize, have three **tabs**: fixed, variable, localize. In every tab can select modification types, or even specific modifications that the user wishes to include as fixed, variable, or localize.
- Possibly display the modification summaries on the search task window, in the form
   ```
       variable: Oxidation of M
       fixed: Carbamidomethyl of C, TMT tag
       localize: 250 modification types
   ```
- In the pruned database, the only decision to be made by the user is whether to keep all uniprot modifications in place, or only the identified ones. We should give that as a checkbox. For all other modification types, it is understood that pruning will only include them if they are confidently identified.
- A custom.txt file for user-defined modifications.
- The multitude of the original modification files should be collapsed into a single file, that should remain untouched. 

Anthony suggested in https://github.com/smith-chem-wisc/MetaMorpheus/issues/286 to "make a reference list of all modification types ", we should address that too. 

Please give me your thoughts/suggestions!

**Comment by acesnik** [comment] 2017-03-27 18:50
* I like the idea of the a single file that's not modifiable; the modification type tag can be used to distinguish between the modifications listed.
* I like the idea of a tree better than tabs if the {fixed,variable,localized} set might expand. Otherwise, if we don't expect the list of categories to expand, let's go with the tabs.
* We should say "localized" instead of "localize," so that they're all adjectives
* I like the custom.txt idea. Maybe we should be able to drag-drop a custom file into the GUI somewhere to have it recognized, too.

**Comment by acesnik** [comment] 2017-03-27 18:56
I do think the modification types (MT) could get out of hand with redundant classes as they are added over time, e.g. ModificationType and Modification_Type, or something like that. That would negatively impact the expected behavior of that string property, so let's make sure the types are formatted similarly and that they're a subset of some easy-to-find reference of all the types.

**Comment by trishorts** [comment] 2017-03-27 18:57
I like:
Instead of the three or four checkboxes next to each modification, corresponding to variable, fixed, localize, have three tabs: fixed, variable, localize. In every tab THE USER can select FROM A LIST OF specific modifications. Could have groups that automatically cause all members to be selected. For example, clicking glyco automatically turns on/off all glyco mods

**Comment by stefanks** [comment] 2017-03-27 19:06
Yea. Actually with the multiple checkboxes gone, it might be possible to go back to the way Morpheus was doing it! Something like
![mods](https://cloud.githubusercontent.com/assets/5972770/24373300/86bf24d0-12f6-11e7-81fb-cd5b1d948cd5.png)

**Comment by stefanks** [comment] 2017-03-27 21:34
More considerations:

- "localize" is confusing to the average user
- Make the default setting to have every single entry checked in the localize tab. Only experts might want to uncheck some entries there.
- What do we do about the modifications specified in the mzLibXML file??? They, and their types are not known prior to start of a task, so it makes no sense to place them in the boxes in the picture above. I think we could have another checkbox to take care of them, namely "localize modifications defined in database file"

**Comment by rmillikin** [comment] 2017-03-27 21:37
I like "database-localized" instead of "localized" to tell you where/why those mods are being localized. 

I also think "whether to keep all uniprot modifications in place, or only the identified ones" should keep all UniProt identified PTMs there by default. The option to uncheck that box is ok. I assume those PTMs have been relatively rigorously identified and we don't want people accidentally deleting things from their databases.

Otherwise I agree with all points

**Comment by stefanks** [comment] 2017-03-27 21:58
Regarding the mzLibXml files, those have some modifications defined in the file. Those modifications should be read in ahead of time, and added as options in the three boxes. They would be mixed in with the original modifications, because of the organization by modification type! This is a nice feature. 

The remaining problem is how to represent the selection of modifications in a parameters file. Possible as pairs of strings: <ModType, ModID>

Now I'm thinking that the original idea of  having a checkbox, "localize uniprot PTMs" is not sufficient. Users might want to cherry-pick which uniprot modifications to localize. 

Anthony suggested having a search bar to find/filter modifications. Possibly filter by modification mass as well.

**Comment by acesnik** [comment] 2017-03-28 16:45
You can filter by any field or property with [this code from proteoform suite](https://github.com/smith-chem-wisc/proteoform-suite/blob/master/ProteoformSuiteInternal/ExtensionMethods.cs#L36).

**Comment by stefanks** [comment] 2017-03-31 16:24
Mostly complete in https://github.com/smith-chem-wisc/MetaMorpheus/pull/301.

Moving some residual ideas to new issues.

**Closed by stefanks** 2017-03-31 16:24 UTC
Labels: GUI Enhancement, High Demand, New Feature
